// Fetch POSTs
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
export const RESET_POSTS = 'RESET_POSTS';

// Fetch POST
export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAILURE = 'FETCH_POST_FAILURE';

// Create POST
export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";

// Delete POST
export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

// Update POST
export const UPDATE_POST = "UPDATE_POST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAILURE = "UPDATE_POST_FAILURE";


// Create COMMENT
export const CREATE_COMMENT = "CREATE_COMMENT";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAILURE = "CREATE_COMMENT_FAILURE";


// Location markers
export const FETCH_MARKERS = "FETCH_MARKERS";
export const FETCH_MARKERS_SUCCESS = "FETCH_MARKERS_SUCCESS";
export const FETCH_MARKERS_FAILURE = "FETCH_MARKERS_FAILURE";


// Fetch LEFTOVERS
export const FETCH_LEFTOVERS = 'FETCH_LEFTOVERS';
export const FETCH_LEFTOVERS_SUCCESS = 'FETCH_LEFTOVERS_SUCCESS';
export const FETCH_LEFTOVERS_FAILURE = 'FETCH_LEFTOVERS_FAILURE';
export const FETCH_MY_LEFTOVERS = 'FETCH_MY_LEFTOVERS';
export const FETCH_MY_LEFTOVERS_SUCCESS = 'FETCH_MY_LEFTOVERS_SUCCESS';
export const FETCH_MY_LEFTOVERS_FAILURE = 'FETCH_MY_LEFTOVERS_FAILURE';


// Fetch LEFTOVER
export const FETCH_LEFTOVER = 'FETCH_LEFTOVER';
export const FETCH_LEFTOVER_SUCCESS = 'FETCH_LEFTOVER_SUCCESS';
export const FETCH_LEFTOVER_FAILURE = 'FETCH_LEFTOVER_FAILURE';

// Create LEFTOVER
export const CREATE_LEFTOVER = "CREATE_LEFTOVER";
export const CREATE_LEFTOVER_SUCCESS = "CREATE_LEFTOVER_SUCCESS";
export const CREATE_LEFTOVER_FAILURE = "CREATE_LEFTOVER_FAILURE";

// Delete LEFTOVER
export const DELETE_LEFTOVER = "DELETE_LEFTOVER";
export const DELETE_LEFTOVER_SUCCESS = "DELETE_LEFTOVER_SUCCESS";
export const DELETE_LEFTOVER_FAILURE = "DELETE_LEFTOVER_FAILURE";

// Update LEFTOVER
export const UPDATE_LEFTOVER = "UPDATE_LEFTOVER";
export const UPDATE_LEFTOVER_SUCCESS = "UPDATE_LEFTOVER_SUCCESS";
export const UPDATE_LEFTOVER_FAILURE = "UPDATE_LEFTOVER_FAILURE";


// User
export const SET_USER = "SET_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

// Fetch ADDRESSEs
export const FETCH_ADDRESSES = 'FETCH_ADDRESSES';
export const FETCH_ADDRESSES_SUCCESS = 'FETCH_ADDRESSES_SUCCESS';
export const FETCH_ADDRESSES_FAILURE = 'FETCH_ADDRESSES_FAILURE';
export const RESET_ADDRESSES = 'RESET_ADDRESSES';

// Create ADDRESSE
export const CREATE_ADDRESS = "CREATE_ADDRESS";
export const CREATE_ADDRESS_SUCCESS = "CREATE_ADDRESS_SUCCESS";
export const CREATE_ADDRESS_FAILURE = "CREATE_ADDRESS_FAILURE";

// Delete ADDRESSE
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_FAILURE = "DELETE_ADDRESS_FAILURE";

// FETCH USERS
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SUCCESS = 'FETCH_ADDRESSES_USERS';
export const FETCH_USERS_FAILURE = 'FETCH_ADDRESSES_USERS';
export const RESET_USERS = 'RESET_USERS';


// Approve LISTING
export const APPROVE_LISTINGS = "APPROVE_LISTINGS";
export const APPROVE_LISTINGS_SUCCESS = "APPROVE_LISTINGS_SUCCESS";
export const APPROVE_LISTINGS_FAILURE = "APPROVE_LISTINGS_FAILURE";



// Logout user
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";

